In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [2]:
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [3]:
one_hot('amazing restaurant',30)

[7, 9]

In [4]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
encoded_reviews

[[13, 19],
 [7, 9],
 [21, 20],
 [2, 1, 2],
 [8, 3, 19],
 [2, 19],
 [4, 3, 12],
 [12, 14],
 [12, 16],
 [20, 19]]

In [5]:
max_length = 4
padded_reviews = pad_sequences(encoded_reviews, max_length, padding='post')
padded_reviews

array([[13, 19,  0,  0],
       [ 7,  9,  0,  0],
       [21, 20,  0,  0],
       [ 2,  1,  2,  0],
       [ 8,  3, 19,  0],
       [ 2, 19,  0,  0],
       [ 4,  3, 12,  0],
       [12, 14,  0,  0],
       [12, 16,  0,  0],
       [20, 19,  0,  0]])

In [6]:
embedded_vector_size = 5

model = Sequential()
model.add(Embedding(vocab_size, embedded_vector_size, input_length=max_length, name='embedding'))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [7]:
X = padded_reviews
y = sentiment

model.compile(optimizer='adam', loss='binary_crossentropy', metrics='accuracy')
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 5)              150       
                                                                 
 flatten (Flatten)           (None, 20)                0         
                                                                 
 dense (Dense)               (None, 1)                 21        
                                                                 
Total params: 171
Trainable params: 171
Non-trainable params: 0
_________________________________________________________________
None


In [8]:
model.fit(X, y, epochs=50, verbose=0)

In [9]:
loss, accuracy = model.evaluate(X,y)
accuracy

1/1 [==============================] - 0s 256ms/step - loss: 0.6321 - accuracy: 1.0000


1.0

In [10]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [11]:
weights[13]

array([ 0.10004383, -0.01283932,  0.0321239 , -0.03870998,  0.02186285],
      dtype=float32)

In [14]:
weights[7]

array([ 0.06159993, -0.01228595,  0.00520674, -0.07743152,  0.02087947],
      dtype=float32)

In [15]:
weights[2]

array([ 0.05835028,  0.08949556, -0.08311538,  0.07013783,  0.02623826],
      dtype=float32)

In [16]:
weights[12]

array([-0.08116169,  0.03056022, -0.09331764,  0.06312554, -0.074068  ],
      dtype=float32)